### ISSUE TITLE
bug: about game size screen 

### ISSUE THREAD

**Issue by iame1l** [Lime365/wow-fishbot#2]
game size only support 1280 * 720? 
and i found window variable width is 1280.
the window maybe is
```python
window = {
    "top": int(game_size["height"] * abs(capture_region - 1)),
    "left": 0,
    "width": int(game_size["width"]),
    "height": int(game_size["height"] * capture_region),
}  
```

it work after i change the width. and efficiency up.  i set game size 3200 * 1800. it work
final,thanks you share the srcipt.very helpful

**Comment by Lime365** [comment]
Hi,
You are right! Updated in main branch :)
